### ISSUE TITLE
relation between PhotSystem and PhotometryFilter

### ISSUE THREAD

**Issue by loumir** [ivoa/modelinstanceinvot-code#13]
I don't understand this sentence in the Readme:
"As there is one file per filter, the PhotometricSystem objects contain only one filter. The merge of several filters in one file is staightforward by the way."

a Photsystem is usually a set of several filters . 
The mapping block can be re-organised  so that the PhotSystem appears only once in the mapping with the instance of filters used for the data .

**Comment by lmichel** [comment]
The script, as it is now, generates one file per filter. If you want get serializations with more than one filter you have to either change both template and script or to merge by hand.
